### PR TITLE
Js styling

### PR DESCRIPTION
**Pull request by jordy1611**
### Type of change made:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing - building tests
- [ ] Formatting - no new features
- [X] Styling- no new features
### Detailed Description (Why is this change required? What problem does it solve? Any challenges that arose while implementing this feature? If so, how were the addressed?)
Formatted Header, App, FormContainer and all the PokeForms
### Files modified:
- [ ] index.html
- [x] App
- [ ] CardContainer
- [ ] PokeCard
- [x] PokeForm
- [ ] Login
- [x] FormContainer
- [ ] index.js
- [ ] Other files:
### Screenshot
Screen Shot 2020-09-12 at 2 32 45 PM

### CODE REVIEW

**Comment by jordy1611** [comment]
Resolved merge conflict. Went with what Ben named properties of state and I moved where the choose pokemon button is located in pokeform

**Review by H-Bo214 — APPROVED** [review]
Really loving the look of our app. Nice job with all of the styling.

**Review by nware1066 — APPROVED** [review]

**Comment by nware1066** [comment]
absolutely love this styling. The pokeball form is perfect for this app

**Review by AurumValian — APPROVED** [review]
This looks amazing! Great job on the styling!

**Pull request merged**
